name: Publish Documentation to GH Pages

on:
  workflow_dispatch:

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "package-a"
  cancel-in-progress: false

jobs:
  publish:
    runs-on: ubuntu-22.04
    steps:
      - run: echo "new release of package-a was created"
